# Generated by Django 4.0.6 on 2022-07-16 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Later', max_length=128)),
                ('assignees', models.ManyToManyField(related_name='tasks', to='api.projectcollaborator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('project_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectpaper')),
            ],
        ),
    ]
