# Generated by Django 4.0.6 on 2022-07-31 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_project_alter_task_project_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depends_on', to='api.task')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='api.task')),
            ],
        ),
    ]
