# Generated by Django 4.0.6 on 2022-08-12 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_taskdependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('project_paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='note', serialize=False, to='api.projectpaper')),
                ('text', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(blank=True, default='Private', max_length=64)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('creator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
