# Generated by Django 4.0.6 on 2022-08-12 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='note',
            name='project_paper',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='note', serialize=False, to='api.projectpaper'),
        ),
    ]
