# Generated by Django 4.0.6 on 2022-08-14 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_creator_id_note_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('website', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('venue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.venue')),
                ('isbn', models.CharField(blank=True, max_length=256, null=True)),
            ],
            bases=('api.venue',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('venue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.venue')),
                ('issn', models.CharField(blank=True, max_length=256, null=True)),
            ],
            bases=('api.venue',),
        ),
        migrations.AddField(
            model_name='paper',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.venue'),
        ),
    ]
