# Generated by Django 4.0.6 on 2022-08-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_keyword_paper_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='keywords',
        ),
    ]
