# Generated by Django 4.0.6 on 2022-08-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_paper_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.ManyToManyField(through='api.PaperKeyword', to='api.keyword'),
        ),
        migrations.AddField(
            model_name='paperkeyword',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paper'),
        ),
    ]
