# Generated by Django 4.0.6 on 2022-08-14 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_venue_reviewers_submissioncomment_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncomment',
            name='reviewer_thread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissioncomment',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.submission'),
        ),
        migrations.AlterField(
            model_name='submissioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
