# Generated by Django 4.0.6 on 2022-08-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_submissioncomment_reviewer_thread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
