# Generated by Django 4.0.6 on 2022-08-24 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_submissioncomment_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewers',
            field=models.ManyToManyField(related_name='review_papers', to=settings.AUTH_USER_MODEL),
        ),
    ]
