# Generated by Django 4.0.6 on 2022-08-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_submission_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
