# Generated by Django 4.0.6 on 2022-08-25 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_submission_reviewers_venueschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=128),
        ),
    ]
