# Generated by Django 4.0.6 on 2022-08-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='VenueSchedule',
            new_name='VenueActivity',
        ),
        migrations.AddField(
            model_name='venue',
            name='keywords',
            field=models.ManyToManyField(related_name='venues', to='api.keyword'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active')], default='DRAFT', max_length=64),
        ),
        migrations.AddField(
            model_name='venue',
            name='domains',
            field=models.ManyToManyField(related_name='venues', to='api.domain'),
        ),
    ]
