# Generated by Django 4.0.6 on 2022-08-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_domain_rename_venueschedule_venueactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domains',
            field=models.ManyToManyField(related_name='projects', to='api.domain'),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(related_name='projects', to='api.keyword'),
        ),
    ]
