# Generated by Django 4.0.6 on 2022-08-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_project_domains_project_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncomment',
            name='hightlight_pos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='keywords',
            field=models.ManyToManyField(related_name='papers', to='api.keyword'),
        ),
    ]
