# Generated by Django 4.0.6 on 2022-08-27 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_hightlight_pos_submissioncomment_highlight_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.submissioncomment'),
        ),
    ]
