# Generated by Django 4.0.6 on 2022-08-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_reviewerproposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewerproposal',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='reviewerproposal',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=64),
        ),
    ]
