# Generated by Django 4.0.6 on 2022-08-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_reviewerproposal_is_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='reviewers',
        ),
    ]
