# Generated by Django 4.0.6 on 2022-08-28 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_reviewer_venue_reviewers_reviewer_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='reviewers',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='reviewers',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='submission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.submission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venueactivity',
            name='activity',
            field=models.CharField(choices=[('Abstract Submission', 'Abstract Submission'), ('Manuscript Submission', 'Manuscript Submission'), ('Peer Review', 'Peer Review'), ('Final Decisions', 'Final Decisions')], max_length=256),
        ),
    ]
