# Generated by Django 4.0.6 on 2022-08-28 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_reviewer_venue_remove_submission_reviewers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='review_papers', through='api.Reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venue',
            name='reviewers',
            field=models.ManyToManyField(related_name='venues', to=settings.AUTH_USER_MODEL),
        ),
    ]
